### ISSUE TITLE
Timber loaded gets confused on Windows Apache Server

### ISSUE THREAD

**Issue by bdbch** [flyntwp/flynt-starter-theme#235] opened 2017-06-29 09:18 UTC
##### Feature
TimberLoader

##### Webserver Stack

* **MAMP PRO 3 for Windows**
  * Apache: 2.2.31
  * MySQL: 5.6.34
  * PHP: 7.0.13

##### System

Windows 10

##### Problem
I presume that Windows backslashes are confusing Timber and the TimberPaths set for loading the files. We tried using `realpath` in combination with `str_replace` to replace all forward slashes with backslashes but it didn't help fixing the problem.

The only solution was to directly load the `index.twig` inside the Timber::fetch function [here](https://github.com/flyntwp/flynt-starter-theme/blob/master/Features/TimberLoader/functions.php#L44). Looks like on Windows Timber doesn't care about the full path but rather uses the paths defined via `returnTimberPaths` directly.

Couldn't figure out a solution yet or really pinpoint down a 100% proof of what is causing this, I'll reinvestigate this, but as I said using `index.twig` instead of `$filePath` [here](https://github.com/flyntwp/flynt-starter-theme/blob/master/Features/TimberLoader/functions.php#L44) on Windows helped fixing it.

**Comment by Qakulukiam** [comment] 2017-07-17 15:59
What exactly do you mean by "confusing Timber"? I'm guessing it isn't rendering anything? Is there an error message?

Either way, generally speaking you don't need to replace forward slashes with backslashes, since PHP should work with forward slashes irrespective of the operating system.

**Comment by bdbch** [comment] 2017-07-17 16:21
Yes there is an error message saying that the twig file could not be found, even though the path is correct. This is fixed as soon as I just use `index.twig` without any path in front of it.

**Comment by o1y** [comment] 2017-12-14 10:03
This is not only limited to Windows systems or Apache-Servers. Twigs Filesystem loader always [combines the loader path with the filename](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Loader/Filesystem.php#L211). Not sure if this has been changed at some time ...

Unfortunately, there is no longer an exception thrown in newer versions of Timber, so this issue becomes very confusing, because Timber isn't rendering any component at all. It would be nice to see a merge of this pull request soon! :)

**Comment by Qakulukiam** [comment] 2017-12-14 12:09
After some more digging, I found that the root cause for this error is the PHP ini setting for open_basedir, which Timber checks here: https://github.com/timber/timber/blob/master/lib/Loader.php#L138

On systems not using this setting ([default is NULL](http://php.net/manual/en/ini.core.php#ini.sect.path-directory)), everything should work fine since the root path ('/') in the Timber loader is not modified.

Since I would rather not set the file to be fetched to just be index.twig (this file could exist in any path added to the `timber/loader/paths` hook), I have made a separate PR for this fix (#265) using a relative path instead.

**Comment by bdbch** [comment] 2017-12-15 00:42
Awesome, no more manually fixes on project init. Good job!

**Comment by bdbch** [comment] 2018-04-18 17:39
Do we have an update on the PR?

**Comment by Qakulukiam** [comment] 2018-07-19 14:04
Merged into master with v0.4.0

**Closed by Qakulukiam** 2018-07-19 14:04 UTC
Labels: bug
